### ISSUE TITLE
Release pulumi-vra

### ISSUE THREAD

**Issue by denopink** [pulumiverse/pulumi-vra#7]
Hi Team,

I'm a part of @schmidtw 's team, is pulumi-vra at a good state to be released?

I'm trying to test some new pulumi code leveraging pulumi-vra, but it's expecting to find a remote release of pulumi-vra.
```console
    error: could not find latest version for provider vra: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumiverse/pulumi-vra/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

**Comment by denopink** [comment]
I'm assuming this need to be patched before release (from my understanding)
https://github.com/pulumiverse/pulumi-vra/pull/8

**Comment by denopink** [comment]
cc: @ringods

**Comment by schmidtw** [comment]
@cobraz / @usrbinkat  / @dirien I originally did the creation of the vra provider & had write access (so I could update/merge/release) but I seem to have lost that access.  We are ready to release the provider, but don't have the ability to do that.  Can you either make a release or grant me access so I can make a release?

Since this is the first release I imaging `v0.0.1` is fine.

Thank you for your help.

**Comment by dirien** [comment]
Hey @schmidtw,

can you make PR to this file and change `push` to `maintain` 

https://github.com/pulumiverse/infra/blob/main/03-members/schmidtw.yaml

This should give you more rights needed to "maintain" the repo

**Comment by ringods** [comment]
@schmidtw your access is in place. This means you should have the right permissions to go forward with the release.
